name: Daily Gold Plan (05:30 & 12:00 Thai)

on:
  schedule:
    # รอบเช้า: 05:30 น. ไทย (คือ 22:30 UTC)
    - cron: '30 22 * * *'  
    # รอบเที่ยง: 12:00 น. ไทย (คือ 05:00 UTC)
    - cron: '0 5 * * *'

  workflow_dispatch: # ปุ่มกดรันมือ

jobs:
  run-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5  # แก้เป็น v5
        with:
          python-version: '3.12'       # แก้เป็น 3.12

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run Python Script
        env: # ไขกุญแจส่งให้ Python
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python daily_gold_plan.py
